/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dataservices.dao.FuncionarioDao;
import java.awt.Color;

/**
 *
 * @author TnahLenovoNote01
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setTitle("Login");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txUsuario = new javax.swing.JTextField();
        txSenha = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btConfirmar);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        txUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txUsuarioKeyPressed(evt);
            }
        });

        txSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txSenhaKeyPressed(evt);
            }
        });

        lbSenha.setText("Senha");

        lbUsuario.setText("Usuário");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txSenha)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUsuario)
                            .addComponent(lbSenha))
                        .addGap(0, 272, Short.MAX_VALUE))
                    .addComponent(txUsuario)
                    .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbSenha)
                .addGap(9, 9, 9)
                .addComponent(txSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed

        String user = txUsuario.getText();
        String senha = txSenha.getText();
        if (user.equals("")) {
            lbMsg.setText("Atenção: Informe seu nome de usuário");
            lbMsg.setForeground(Color.red);
            repaint();
        } else if (senha.equals("")) {
            lbMsg.setText("Atenção: Informe sua senha");
            lbMsg.setForeground(Color.red);
            repaint();
        } else if (funcDao.verifUser(user)) {
            if (funcDao.verifSenha(user, senha)) {
                if (funcDao.getCargo(user, senha).equals("Gerente")) {
                    new PrincipalGerente(funcDao.getNome(user, senha)).setVisible(true);

                    dispose();
                } else if (funcDao.getCargo(user, senha).equals("Gerente de caixa")) {
                    new PrincipalGerenteCaixa(funcDao.getNome(user, senha)).setVisible(true);
                    dispose();
                } else {
                    new PrincipalOperador(funcDao.getNome(user, senha)).setVisible(true);
                    dispose();
                }
            } else {
                lbMsg.setText("Atenção: Senha incorreta");
                lbMsg.setForeground(Color.red);
                repaint();
            }
        } else {
            lbMsg.setText("Atenção: Usuário não existente");
            lbMsg.setForeground(Color.red);
            repaint();
        }


    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txUsuarioKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String user = txUsuario.getText();
            String senha = txSenha.getText();
            if (user.equals("")) {
                lbMsg.setText("Atenção: Informe seu nome de usuário");
                lbMsg.setForeground(Color.red);
                repaint();
            } else if (senha.equals("")) {
                lbMsg.setText("Atenção: Informe sua senha");
                lbMsg.setForeground(Color.red);
                repaint();
            } else if (funcDao.verifUser(user)) {
                if (funcDao.verifSenha(user, senha)) {
                    if (funcDao.getCargo(user, senha).equals("Gerente")) {
                        new PrincipalGerente(funcDao.getNome(user, senha)).setVisible(true);

                        dispose();
                    } else if (funcDao.getCargo(user, senha).equals("Gerente de caixa")) {
                        new PrincipalGerenteCaixa(funcDao.getNome(user, senha)).setVisible(true);
                        dispose();
                    } else {
                        new PrincipalOperador(funcDao.getNome(user, senha)).setVisible(true);
                        dispose();
                    }
                } else {
                    lbMsg.setText("Atenção: Senha incorreta");
                    lbMsg.setForeground(Color.red);
                    repaint();
                }
            } else {
                lbMsg.setText("Atenção: Usuário não existente");
                lbMsg.setForeground(Color.red);
                repaint();
            }
        }
    }//GEN-LAST:event_txUsuarioKeyPressed

    private void txSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txSenhaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String user = txUsuario.getText();
            String senha = txSenha.getText();
            if (user.equals("")) {
                lbMsg.setText("Atenção: Informe seu nome de usuário");
                lbMsg.setForeground(Color.red);
                repaint();
            } else if (senha.equals("")) {
                lbMsg.setText("Atenção: Informe sua senha");
                lbMsg.setForeground(Color.red);
                repaint();
            } else if (funcDao.verifUser(user)) {
                if (funcDao.verifSenha(user, senha)) {
                    if (funcDao.getCargo(user, senha).equals("Gerente")) {
                        new PrincipalGerente(funcDao.getNome(user, senha)).setVisible(true);

                        dispose();
                    } else if (funcDao.getCargo(user, senha).equals("Gerente de caixa")) {
                        new PrincipalGerenteCaixa(funcDao.getNome(user, senha)).setVisible(true);
                        dispose();
                    } else {
                        new PrincipalOperador(funcDao.getNome(user, senha)).setVisible(true);
                        dispose();
                    }
                } else {
                    lbMsg.setText("Atenção: Senha incorreta");
                    lbMsg.setForeground(Color.red);
                    repaint();
                }
            } else {
                lbMsg.setText("Atenção: Usuário não existente");
                lbMsg.setForeground(Color.red);
                repaint();
            }
        }
    }//GEN-LAST:event_txSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    FuncionarioDao funcDao = new FuncionarioDao();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField txSenha;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables

}
